services:
    shortinette:
        container_name: shortinette
        build:
            context: shortinette
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
            

    dashboard:
        container_name: dashboard
        build:
            context: dashboard
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
