services:

  rust-short:
    container_name: rust-short
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - BASE_PATH=${PWD}
    volumes:
      - "./rust:/app/rust"
      - "./data:/app/data"
    profiles:
      - rust