version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_ORGANISATION: ${GITHUB_ORGANISATION}
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      PORT: 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db:
  