name: Biome

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'website/**'

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        working-directory: './website'
        run: biome ci .
