name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '*' ]
    env:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      ORGA_GITHUB: ${{ secrets.ORGA_GITHUB }}
        
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
        working-directory: './shortinette'
      - name: Build
        run: go build -v ./...
        working-directory: './shortinette'
      - name: Set up Git credentials
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git config --global url."https://${{ secrets.TOKEN_GITHUB }}@github.com".insteadOf "https://github.com/"
      - name: Run tests
        run: go test ./...
        working-directory: './shortinette'

