name: golangci-lint
on:
  push:
    paths:
      - 'app/**.go'
      - 'app/go.mod'
      - 'app/go.sum'
  pull_request:
    paths:
      - 'app/**.go'
      - 'app/go.mod'
      - 'app/go.sum'

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
      - name: Run golangci-lint
        run: golangci-lint run
        working-directory: './app'
        
