name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN_GITHUB }}
        issue-message: "Hello @${{ github.event.issue.user.login }}! 👋 Thank you for opening your first issue in this repository. We appreciate your contribution to our project! 

        A maintainer will review your issue soon. If you're reporting a bug, please provide as much detail as possible – including steps to reproduce, expected vs. actual behavior, and any relevant logs or screenshots. The more information you can provide, the better we can assist you.

        Thank you for helping us improve our project!"

        pr-message: "Welcome @${{ github.event.pull_request.user.login }}! 🎉 We're excited to see your first pull request to this project. Thank you for contributing!

        A maintainer will review your changes shortly. In the meantime, please ensure your PR includes:
        - A clear description of the changes
        - Any relevant documentation updates
        - Tests, if applicable

        We value your effort and look forward to collaborating with you. If you have any questions, feel free to ask in the PR comments.

        Thanks again for your contribution!"
